name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libopus0 \
          libvpx-dev \
          libevent-2.1-7 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-libav \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-alsa \
          gstreamer1.0-pulseaudio \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 \
          libgles2-mesa \
          libx264-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install pytest pytest-html

    - name: Install Playwright and browsers
      run: |
        pip install playwright
        sudo playwright install --with-deps

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run Playwright tests on ${{ matrix.browser }}
      env:
        PLAYWRIGHT_BROWSERS_PATH: 0
      run: |
        export PLAYWRIGHT_BROWSERS_PATH=0
        pytest --html=report_${{ matrix.browser }}.html --self-contained-html

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: playwright-test-reports
        path: |
          report_chromium.html
          report_firefox.html
          report_webkit.html
