name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libopus0 \
          libvpx-dev \
          libevent-2.1-7 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-libav \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-alsa \
          gstreamer1.0-pulseaudio \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 \
          libgles2-mesa \
          libx264-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html pytest-metadata

    - name: Install Playwright and browsers
      run: |
        pip install playwright
        python -m playwright install --with-deps

    - name: Install Flask
      run: pip install Flask
    - name: Start Flask server
      run: python store/app.py &

    - name: Wait for server to start
      run: sleep 5

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run Playwright tests on ${{ matrix.browser }}
      run: |
        pytest --html=report_${{ matrix.browser }}.html --self-contained-html -s -v --browser ${{ matrix.browser }}
        mkdir -p screenshots
        mv screenshot*.png screenshots/

    - name: Capture and upload screenshots on failure
      if: always()  # Upload artifacts regardless of test outcome
      run: |
        mkdir -p screenshots/screenshots_${{ github.sha }}_${{ matrix.browser }}
        mv screenshots/*.png screenshots/screenshots_${{ github.sha }}_${{ matrix.browser }} || echo "No screenshots found to move."

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: playwright-test-reports
        path: |
          report_chromium.html
          report_firefox.html
          report_webkit.html
          screenshots/
